### ISSUE TITLE
how are q-scores recalculated for merged reads?

### ISSUE THREAD

**Issue by rrohwer** [nisheth/MeFiT#4]
Hi, this is not exactly a bug report, but my e-mail to the corresponding author bounced.

After merging reads using the CASPER algorithm, MeFiT performs quality score-based QC using max ee. My question is: which algorithm is used to recalculate post-merging q scores? 

Thanks!

Robin

**Comment by kopardev** [comment]
Check out:
  * https://bmcbioinformatics.biomedcentral.com/articles/10.1186/s12859-016-1358-1
  * https://bmcbioinformatics.biomedcentral.com/articles/10.1186/1471-2105-15-S9-S10
for details.
