### ISSUE TITLE
casper is not found in the link  http://best.snu.ac.kr/casper

### ISSUE THREAD

**Issue by robi56** [nisheth/MeFiT#5]
casper is not found in the link  http://best.snu.ac.kr/casper. Could you please provide the  the download link @nisheth

**Comment by kopardev** [comment]
Thanks for pointing this out. [Casper](https://bmcbioinformatics.biomedcentral.com/articles/10.1186/1471-2105-15-S9-S10) is indeed no longer available for download. We have reached out to the authors of CASPER.

Another alternative would be switch to a different pair-end reads merging tool like [PEAR](https://academic.oup.com/bioinformatics/article/30/5/614/247231) which is available [here](https://cme.h-its.org/exelixis/web/software/pear/).

**Comment by robi56** [comment]
@kopardev , I am trying to install MeFIT at Ubuntu 20 but I have failed. Have you any feedback to install MeFit?

**Comment by kopardev** [comment]
Casper is now available [here](https://github.com/skwonPNU/casper).
